### ISSUE TITLE
cp -rv in Makefile does not work on OS X

### ISSUE THREAD

**Issue by gz-c** [skycoin/docs#60] opened 2018-03-03 00:18 UTC
`cp -rv` fails on OS X, `-rv` is not recognized as options

```sh
» make build
rm -rf content/*
cp -rv _data/* content/
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
make: *** [build] Error 64
```

**Comment by olemis** [comment] 2018-03-04 18:06
@gz-c I tried that in macOS when I developed the `Makefile` ... this is a weird issue I cannot reproduce locally . This is the output I get

```sh
$ make run
rm -rf content/*
cp -rv _data/* content/
_data/_index.md -> content/_index.md
_data/devdocs -> content/devdocs
_data/devdocs/_index.md -> content/devdocs/_index.md
_data/devdocs/examples -> content/devdocs/examples
_data/devdocs/examples/_index.md -> content/devdocs/examples/_index.md
_data/devdocs/guides -> content/devdocs/guides
_data/devdocs/guides/_index.md -> content/devdocs/guides/_index.md
_data/devdocs/guides/block_chain.md -> content/devdocs/guides/block_chain.md
_data/devdocs/guides/intro.md -> content/devdocs/guides/intro.md
_data/devdocs/guides/p2p_network.md -> content/devdocs/guides/p2p_network.md
_data/devdocs/guides/transactions.md -> content/devdocs/guides/transactions.md
_data/devdocs/references -> content/devdocs/references
_data/devdocs/references/_index.md -> content/devdocs/references/_index.md
_data/devdocs/references/intro.md -> content/devdocs/references/intro.md
_data/devdocs/references/p2p_networking.md -> content/devdocs/references/p2p_networking.md
_data/future-plans -> content/future-plans
_data/future-plans/_index.md -> content/future-plans/_index.md
_data/glossary -> content/glossary
_data/glossary/51-percent-attack.yaml -> content/glossary/51-percent-attack.yaml
_data/glossary/_index.md -> content/glossary/_index.md
_data/glossary/block-height.yaml -> content/glossary/block-height.yaml
_data/glossary/block-sequence-number.yaml -> content/glossary/block-sequence-number.yaml
_data/glossary/distribution-addresses.yaml -> content/glossary/distribution-addresses.yaml
_data/glossary/head-block.yaml -> content/glossary/head-block.yaml
_data/glossary/locktime.yaml -> content/glossary/locktime.yaml
_data/glossary/maximum-message-length.yaml -> content/glossary/maximum-message-length.yaml
_data/glossary/p2pkh-address.yaml -> content/glossary/p2pkh-address.yaml
_data/glossary/p2sh-address.yaml -> content/glossary/p2sh-address.yaml
_data/glossary/private-key.yaml -> content/glossary/private-key.yaml
_data/glossary/public-key.yaml -> content/glossary/public-key.yaml
_data/glossary/standard-transaction.yaml -> content/glossary/standard-transaction.yaml
_data/img -> content/img
_data/img/coinjoin.png -> content/img/coinjoin.png
_data/img/skycoin-transaction-data-structure.png -> content/img/skycoin-transaction-data-structure.png
_data/user-guides -> content/user-guides
_data/user-guides/bitcoin -> content/user-guides/bitcoin
_data/user-guides/bitcoin/balance.png -> content/user-guides/bitcoin/balance.png
_data/user-guides/bitcoin/bitcoin-data-structure.jpg -> content/user-guides/bitcoin/bitcoin-data-structure.jpg
_data/user-guides/bitcoin/How bitcoin transactions works?.md -> content/user-guides/bitcoin/How bitcoin transactions works?.md
_data/user-guides/bitcoin/how-bitcoin-miners-works-2.jpg -> content/user-guides/bitcoin/how-bitcoin-miners-works-2.jpg
_data/user-guides/bitcoin/how-bitcoin-miners-works.jpg -> content/user-guides/bitcoin/how-bitcoin-miners-works.jpg
_data/user-guides/bitcoin/How-bitcoin-transaction-work-2.png -> content/user-guides/bitcoin/How-bitcoin-transaction-work-2.png
_data/user-guides/bitcoin/how-bitcoin-transaction-work.jpg -> content/user-guides/bitcoin/how-bitcoin-transaction-work.jpg
_data/user-guides/bitcoin/Multi-wallet-technique.png -> content/user-guides/bitcoin/Multi-wallet-technique.png
_data/user-guides/bitcoin/private-public-key.png -> content/user-guides/bitcoin/private-public-key.png
_data/user-guides/bitcoin/why-bitcoin-transactions-are-not-anonymous-multiple-addresses.png -> content/user-guides/bitcoin/why-bitcoin-transactions-are-not-anonymous-multiple-addresses.png
_data/user-guides/bitcoin/why-bitcoin-transactions-are-not-anonymous.png -> content/user-guides/bitcoin/why-bitcoin-transactions-are-not-anonymous.png
_data/user-guides/bitcoin/Why-bitcoin-transactions-are-not-anonymous?.md -> content/user-guides/bitcoin/Why-bitcoin-transactions-are-not-anonymous?.md
_data/user-guides/blockchain -> content/user-guides/blockchain
_data/user-guides/blockchain/Block-Header-Internal-04.png -> content/user-guides/blockchain/Block-Header-Internal-04.png
_data/user-guides/blockchain/blockchain-data-structure-linked-list.jpg -> content/user-guides/blockchain/blockchain-data-structure-linked-list.jpg
_data/user-guides/blockchain/what is blockchain?.md -> content/user-guides/blockchain/what is blockchain?.md
_data/user-guides/blockchain/What-is-Blockchain-05.png -> content/user-guides/blockchain/What-is-Blockchain-05.png
_data/user-guides/cx -> content/user-guides/cx
_data/user-guides/cx/main benefits.md -> content/user-guides/cx/main benefits.md
_data/user-guides/cx/what cx can accomplish?.md -> content/user-guides/cx/what cx can accomplish?.md
_data/user-guides/skycoin -> content/user-guides/skycoin
_data/user-guides/skycoin/capitalize-btc.png -> content/user-guides/skycoin/capitalize-btc.png
_data/user-guides/skycoin/coinjoin-hardening.png -> content/user-guides/skycoin/coinjoin-hardening.png
_data/user-guides/skycoin/coinjoin-is-correct-capitalization.png -> content/user-guides/skycoin/coinjoin-is-correct-capitalization.png
_data/user-guides/skycoin/Finding-a-Transaction.png -> content/user-guides/skycoin/Finding-a-Transaction.png
_data/user-guides/skycoin/how skycoin fixes bitcoin transactions privacy.md -> content/user-guides/skycoin/how skycoin fixes bitcoin transactions privacy.md
_data/user-guides/skycoin/How to purchase Skycoin.md -> content/user-guides/skycoin/How to purchase Skycoin.md
_data/user-guides/skycoin/How-skycoin-server-verify.png -> content/user-guides/skycoin/How-skycoin-server-verify.png
_data/user-guides/skycoin/how-skycoin-transactions-work.png -> content/user-guides/skycoin/how-skycoin-transactions-work.png
_data/user-guides/skycoin/skycoin-transaction-data-structure.png -> content/user-guides/skycoin/skycoin-transaction-data-structure.png
_data/user-guides/skycoin/this-is-not-a-good-first-page.png -> content/user-guides/skycoin/this-is-not-a-good-first-page.png
_data/user-guides/skycoin/Unspent-transaction-output.png -> content/user-guides/skycoin/Unspent-transaction-output.png
_data/user-guides/skycoin/what is a skycoin transaction?.md -> content/user-guides/skycoin/what is a skycoin transaction?.md
_data/user-guides/wallets -> content/user-guides/wallets
_data/user-guides/wallets/backup_wallet.png -> content/user-guides/wallets/backup_wallet.png
_data/user-guides/wallets/download_backup.png -> content/user-guides/wallets/download_backup.png
_data/user-guides/wallets/downloads.png -> content/user-guides/wallets/downloads.png
_data/user-guides/wallets/drag_skycoin_app.png -> content/user-guides/wallets/drag_skycoin_app.png
_data/user-guides/wallets/hidden_dir.jpg -> content/user-guides/wallets/hidden_dir.jpg
_data/user-guides/wallets/How to install skycoin wallet.md -> content/user-guides/wallets/How to install skycoin wallet.md
_data/user-guides/wallets/how to recover a skycoin wallet.md -> content/user-guides/wallets/how to recover a skycoin wallet.md
_data/user-guides/wallets/How to secure your skycoin wallet.md -> content/user-guides/wallets/How to secure your skycoin wallet.md
_data/user-guides/wallets/open_bin.png -> content/user-guides/wallets/open_bin.png
_data/user-guides/wallets/pre_delete_wallet.png -> content/user-guides/wallets/pre_delete_wallet.png
_data/user-guides/wallets/pro_delete_wallets.png -> content/user-guides/wallets/pro_delete_wallets.png
_data/user-guides/wallets/Scanning Wallet.md -> content/user-guides/wallets/Scanning Wallet.md
_data/user-guides/wallets/scanning_wallet.jpg -> content/user-guides/wallets/scanning_wallet.jpg
_data/user-guides/wallets/seedkey.png -> content/user-guides/wallets/seedkey.png
_data/user-guides/wallets/skycoin_icon.png -> content/user-guides/wallets/skycoin_icon.png
_data/user-guides/wallets/skycoin_restarted.png -> content/user-guides/wallets/skycoin_restarted.png
_data/user-guides/wallets/sync.png -> content/user-guides/wallets/sync.png
_data/user-guides/wallets/wallet.jpg -> content/user-guides/wallets/wallet.jpg
_data/user-guides/wallets/wallet2.png -> content/user-guides/wallets/wallet2.png
touch content/.gitkeep
find content/* -type f -name "*.md" -exec sh -c 'cat _includes/references.md >> "{}" ' \;
hugo serve -D

                   | EN
+------------------+----+
  Pages            | 39
  Paginator pages  |  0
  Non-page files   | 51
  Static files     | 31
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Total in 141 ms
Watching for changes in $GOPATH/src/github.com/skycoin/docs/{content,data,layouts,static,themes}
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

... and this is my system information 

```sh

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2659

$ uname -a
Darwin simelo-mbp.local 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64
```

**Comment by gz-c** [comment] 2018-03-04 22:54
Should it be `-Rv`?

**Comment by gz-c** [comment] 2018-03-04 22:56
ok, the problem is that it fails when there is no existing `content/` folder

**Comment by olemis** [comment] 2018-03-05 00:16
fixed in master

**Closed as completed by olemis** 2018-03-05 00:16 UTC
Labels: stdev, wip
